### ISSUE TITLE
consumer semantic tokens: defining in code

### ISSUE THREAD

**Issue by sashafirsov** [EPA-WG/custom-element-dist#17]
AC:
* source level theme definition
* support for generic theme interface
* implementation of theme with interface 
* theme source editor with validations and visual hints like colors or click-through navigation

Parent story #16

**Comment by sashafirsov** [comment]
# 🤔 Dev notes. 
3 options: TypeScript, CSS, `.tokens.json`

## TypeScript
Allows to create the type definition as `ConsumerSemanticTheme` interface, theme object is an instance of type. 
The integrity would be supported on TS compiler level, documentation generated by JsDocs or [Decorators](https://www.typescriptlang.org/docs/handbook/decorators.html)

## CSS
The theme is defined as set of mixins - classes, the hierarchy defined by class nesting. 

Final CSS is generated from source one and comprise the mixins and css variables.

The theme `.tokens.json` is generated from the source CSS.

## .tokens.json
is edited say by [Design Tokens](https://www.figma.com/community/plugin/888356646278934516/design-tokens) Figma plugin or by [Amazon Style Dictionary](https://amzn.github.io/style-dictionary)

**Comment by sashafirsov** [comment]
# Native CSS theme support
[CSS color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) allows to enforce the theme for particular element

```css
:root {
  color-scheme: light dark;
}
.element {
  color: light-dark(black, white);
  background-color: light-dark(white, black);
}

/* OR */
@media (prefers-color-scheme: light) {
  .element {
    color: black;
    background-color: white;
  }
}

@media (prefers-color-scheme: dark) {
  .element {
    color: white;
    background-color: black;
  }
}
```
use the [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) [<color> function](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units/CSS_Value_Functions#color_functions) to set the foreground and background colors.
